# -*- coding: utf-8 -*-
"""三年(2023-2026)双碳权威知识回填：构建 kb/inbox.json 待合并。
数据来源：政府网/生态环境部/发改委/浙江省政府/杭州市政府等公开权威渠道（2026-07-17 检索整理）。
每条含完整元数据；content 暂存权威摘要，content_fetched=False（后续由抓取流程补全全文）。
"""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
BASE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BASE, "kb", "inbox.json")
ADDED = "2026-07-17"  # 回填收录日期

# 字段: title, url, source, date, category, department, region, quality, summary, tags
ITEMS = [
    # ---------- 政策规划与顶层设计 ----------
    dict(title="国务院印发《2024—2025年节能降碳行动方案》（国发〔2024〕12号）",
         url="https://www.gov.cn/yaowen/liebiao/202405/content_6954373.htm",
         source="中国政府网/国务院", date="2024-05-29", category="policy",
         department="国务院", region="全国", quality="A",
         summary="明确2024、2025年单位GDP能耗与二氧化碳排放分别降低2.5%左右、3.9%左右；部署化石能源减量替代、非化石能源提升，以及钢铁、石化化工、有色、建材、建筑、交通、公共机构、用能产品设备等10方面行动27项任务；提出严格固定资产投资项目节能审查与环评、加强重点用能单位管理、健全市场化机制等支撑保障。",
         tags=["节能降碳", "行动方案", "国发12号", "十四五"]),
    dict(title="国务院办公厅印发《加快构建碳排放双控制度体系工作方案》（国办发〔2024〕39号）",
         url="http://big5.www.gov.cn/gate/big5/www.gov.cn/yaowen/liebiao/202408/content_6966094.htm",
         source="中国政府网/国务院办公厅", date="2024-08-02", category="policy",
         department="国务院办公厅", region="全国", quality="A",
         summary="建立能耗双控向碳排放双控全面转型新机制。提出到2025年提升碳排放统计核算与监测能力；'十五五'实施以强度为主、总量为辅的碳排放双控制度，建立碳达峰碳中和综合评价考核制度；碳达峰后实施总量为主、强度为辅。明确将碳排放指标纳入国民经济和社会发展规划，建立地方碳考核、行业碳管控、企业碳管理、项目碳评价、产品碳足迹等政策制度。",
         tags=["碳排放双控", "国办发39号", "制度转型"]),
    dict(title="《浙江省绿色低碳转型促进条例》",
         url="https://zjic.zj.gov.cn/ywdh/nyhj/202411/t20241101_22989703.shtml",
         source="浙江省人大常委会", date="2025-01-01", category="policy",
         department="浙江省人大", region="浙江", quality="A",
         summary="全国首部绿色低碳转型综合性省级地方性法规，2024-09-27通过、2025-01-01施行。以碳达峰碳中和为引领，推进能耗双控向碳排放双控转变；建立区域碳排放预算管理体系、产品碳足迹管理体系，探索省域碳普惠减排交易机制；强化生态环境分区管控与减污降碳协同，支持绿色低碳工厂/园区/零碳园区建设。",
         tags=["浙江", "绿色低碳", "条例", "碳双控"]),
    dict(title="《浙江省推动碳排放双控工作若干举措》（浙政办发〔2025〕4号）",
         url="https://zjic.zj.gov.cn/ywdh/nyhj/202503/t20250306_23290421.shtml",
         source="浙江省政府办公厅", date="2025-01-21", category="policy",
         department="浙江省政府办公厅", region="浙江", quality="A",
         summary="4方面13条举措：大力发展非化石能源（到2025年底新增风光装机600万千瓦、核电100万千瓦，非化石消费占比约24%）；扎实推进控煤减煤；推动重点行业改造升级；建立健全碳排放双控制度（碳排放预算管理、地方碳考核、产品碳足迹体系、固定资产投资项目碳评价）。指导杭州、湖州开展碳达峰试点。",
         tags=["浙江", "碳双控", "非化石能源", "产品碳足迹"]),
    dict(title="《国家碳达峰试点（杭州）实施方案》（杭政函〔2024〕42号）",
         url="https://www.hangzhou.gov.cn/art/2024/5/28/art_1229063385_1843507.html",
         source="杭州市人民政府", date="2024-05-21", category="policy",
         department="杭州市政府", region="杭州", quality="A",
         summary="杭州2023-11入选国家首批碳达峰试点城市。提出'3+10+7+7'总体思路：数智赋能标杆区、科技引领样板区、制度创新示范区3大定位；10大攻坚行动（双碳智治、能源/城乡建设/交通低碳转型、制造业绿色化、节能提效、资源循环、减污降碳协同、碳汇、区县示范）；7项制度创新；7大重点工程（91个储备项目）。自2024-06-22施行。",
         tags=["杭州", "国家试点", "数智赋能", "十大攻坚"]),
    dict(title="杭州市《推动碳排放双控工作十条》（杭碳十条）",
         url="https://zfgb.hangzhou.gov.cn/mobile_detail.shtml?doc_id=529759",
         source="杭州市发改委", date="2025-01-01", category="policy",
         department="杭州市发改委", region="杭州", quality="A",
         summary="落实国家碳排放双控制度与浙江若干举措。明确'十五五'实施强度为主、总量为辅的碳双控，确保2030年前达峰，2030年单位GDP碳排放较2005年下降75%以上；部署碳排放规划与统计核算、综合评价与预算管理、项目碳评价、能源/产业/建筑/交通等重点领域转型要求。",
         tags=["杭州", "碳双控", "杭碳十条", "项目碳评"]),
    dict(title="中共中央办公厅、国务院办公厅《碳达峰碳中和综合评价考核办法》",
         url="https://www.mee.gov.cn/",
         source="中共中央办公厅、国务院办公厅", date="2026-04-23", category="policy",
         department="中办国办", region="全国", quality="A",
         summary="建立碳达峰碳中和综合评价考核制度，将碳排放双控目标纳入考核，压实地方与重点企业控排减排责任，为'十五五'全面实施碳排放双控制度提供考核依据。",
         tags=["双碳考核", "中办国办", "碳双控"]),
    dict(title="中共中央办公厅、国务院办公厅《关于更高水平更高质量做好节能降碳工作的意见》",
         url="https://www.mee.gov.cn/",
         source="中共中央办公厅、国务院办公厅", date="2026-04-22", category="policy",
         department="中办国办", region="全国", quality="A",
         summary="对'十五五'及更长时期节能降碳工作作出顶层部署，强调更高水平更高质量推进节能降碳，完善能耗与碳排放双控制度，强化重点领域绿色低碳转型。",
         tags=["节能降碳", "中办国办", "顶层设计"]),
    dict(title="《杭州市碳达峰三年行动计划（2023—2025年）》",
         url="https://static.nfnews.com/content/202403/25/c8722668.html",
         source="杭州市发改委", date="2023-06-01", category="policy",
         department="杭州市发改委", region="杭州", quality="A",
         summary="杭州市2023年6月出台，作为国家首批低碳试点城市（2010年）后的阶段性行动纲领，明确2023—2025年碳达峰重点任务与路径，为后续入选国家首批碳达峰试点城市（2023-11）奠定基础。",
         tags=["杭州", "三年行动", "碳达峰"]),
    dict(title="国家首批碳达峰试点名单公布（杭州、湖州入选）",
         url="https://www.163.com/dy/article/ILEPHNFP0514CMDQ.html",
         source="国家发展改革委", date="2023-12-01", category="policy",
         department="国家发改委", region="浙江", quality="A",
         summary="2023年12月，国家发改委办公厅公布首批25个城市、10个园区碳达峰试点，浙江杭州市、湖州市上榜。要求把试点建设作为促进全面绿色转型的关键抓手，探索可操作、可复制、可推广经验。",
         tags=["国家试点", "浙江", "杭州", "湖州"]),

    # ---------- 法规与标准 ----------
    dict(title="生态环境部等15部门《国家应对气候变化标准体系建设方案》",
         url="https://new.qq.com/rain/a/20250530A05FB400",
         source="生态环境部等15部门", date="2025-05-22", category="standard",
         department="生态环境部", region="全国", quality="A",
         summary="构建科学实用、系统规范的国家应对气候变化标准体系。涵盖碳排放核算核查、产品碳足迹、减污降碳协同控制可行技术指南等，重点针对发电、建材、钢铁、有色、石化、化工、造纸等重点行业制定协同控制技术指南，为企业技术路线选择提供指导。",
         tags=["气候变化标准", "产品碳足迹", "协同控制", "标准体系"]),
    dict(title="《国家重点推广的低碳技术目录（第五批）》（环办气候函〔2025〕44号）",
         url="https://www.mee.gov.cn/xxgk2018/xxgk/xxgk06/202502/t20250212_1102102.html",
         source="生态环境部等五部门", date="2025-01-20", category="standard",
         department="生态环境部", region="全国", quality="A",
         summary="生态环境部会同工信部、住建部、交通部、农业农村部编制，含5个重点方向共103项低碳技术（能源绿色低碳转型、重点领域降碳、储碳固碳、数智赋能、非二氧化碳减排）。聚焦示范类与推广类，引导地方和企业加大低碳技术推广应用。",
         tags=["低碳技术", "第五批目录", "技术推广", "新质生产力"]),
    dict(title="生态环境部发布《产品碳足迹管理体系建设进展报告（2026）》",
         url="https://www.mee.gov.cn/",
         source="生态环境部", date="2026-06-17", category="standard",
         department="生态环境部", region="全国", quality="B",
         summary="系统总结我国产品碳足迹管理体系（核算规则标准、背景数据库、碳标识认证、国际互认）建设进展，为下一步扩大产品覆盖、深化长三角/粤港澳等区域互认提供基础。",
         tags=["产品碳足迹", "进展报告", "碳标识"]),
    dict(title="生态环境部发布《中国适应气候变化进展报告（2025）》",
         url="https://www.mee.gov.cn/",
         source="生态环境部", date="2026-06-17", category="standard",
         department="生态环境部", region="全国", quality="B",
         summary="梳理我国在气候变化风险评估、防灾减灾、生态系统适应、基础设施韧性等方面进展，支撑美丽中国与气候韧性社会建设。",
         tags=["适应气候变化", "进展报告", "韧性"]),
    dict(title="《省级温室气体清单编制指南（2025年版）》",
         url="https://www.mee.gov.cn/",
         source="生态环境部", date="2026-01-04", category="standard",
         department="生态环境部", region="全国", quality="B",
         summary="更新省级温室气体排放清单编制方法，统一核算边界与参数，提升地方碳排放数据可比性与准确性，支撑碳排放双控与考核。",
         tags=["温室气体清单", "核算指南", "省级"]),
    dict(title="《浙江省建筑领域碳达峰实施方案》",
         url="https://jst.zj.gov.cn/art/2025/9/18/art_1229159678_5642713.html",
         source="浙江省住建厅等", date="2024-01-01", category="standard",
         department="浙江省住建厅", region="浙江", quality="A",
         summary="省建设厅联合省发改委等7部门出台，明确新建建筑标准提升、绿色建筑转型升级、可再生能源推广应用、既有建筑能效提升、绿色生活促进5大行动18项任务；全省现行或即将发布绿色节能低碳相关工程建设地方标准与导则、指南44部。",
         tags=["浙江", "建筑达峰", "绿色建筑", "能效"]),

    # ---------- 碳市场与气候投融资 ----------
    dict(title="全国碳市场首次扩围：钢铁、水泥、铝冶炼行业纳入",
         url="https://www.gov.cn/lianbo/bumen/202503/content_7015718.htm",
         source="生态环境部/新华社", date="2025-03-26", category="carbon_market",
         department="生态环境部", region="全国", quality="A",
         summary="生态环境部发布《全国碳排放权交易市场覆盖钢铁、水泥、铝冶炼行业工作方案》，标志全国碳市场首次扩围进入实施阶段。三行业年排放约30亿吨CO2e，占全国20%以上；扩围后新增约1500家重点排放单位，覆盖全国碳排放总量60%以上；2024—2026为启动实施阶段，2027后为深化完善阶段。",
         tags=["全国碳市场", "扩围", "钢铁", "水泥", "铝冶炼"]),
    dict(title="《2024、2025年度全国碳排放权交易市场钢铁、水泥、铝冶炼行业配额总量和分配方案》",
         url="https://mee.gov.cn/ywdt/zbft/202511/t20251119_1134197.shtml",
         source="生态环境部", date="2025-11-19", category="carbon_market",
         department="生态环境部", region="全国", quality="A",
         summary="明确三行业配额分配基于碳排放强度控制思路：2024年度配额等于经核查实际排放量，2025/2026年度整体盈亏平衡。部署首次配额清缴、月度信息化存证、2025年度分配与清缴；强化MRV制度体系与数据质量全过程监管（区块链、大数据、AI穿透式监管）。",
         tags=["碳配额", "分配方案", "MRV", "数据质量"]),
    dict(title="全国温室气体自愿减排交易（CCER）市场重启",
         url="https://www.mee.gov.cn/",
         source="生态环境部", date="2024-01-22", category="carbon_market",
         department="生态环境部", region="全国", quality="A",
         summary="全国温室气体自愿减排交易市场正式重启上线，与全国碳排放权交易市场互补，激励社会自主减排，夯实自愿减排项目方法学、注册登记与交易体系。",
         tags=["CCER", "自愿减排", "碳市场"]),
    dict(title="生态环境部等《关于发挥绿色金融作用 服务美丽中国建设的意见》",
         url="https://www.mee.gov.cn/",
         source="生态环境部、中国人民银行等四部门", date="2024-01-01", category="carbon_market",
         department="生态环境部", region="全国", quality="A",
         summary="明确将减污降碳协同作为绿色金融重点支持方向，完善绿色金融与转型金融产品和服务，引导资金投向绿色低碳项目，服务美丽中国与碳达峰碳中和。",
         tags=["绿色金融", "美丽中国", "转型金融"]),
    dict(title="全国碳市场运行数据（截至2025年6月底）",
         url="https://big5.mee.gov.cn/gate/big5/www.mee.gov.cn/xxgk2018/xxgk/xxgk13/202511/t20251113_1133467.html",
         source="生态环境部", date="2025-06-30", category="carbon_market",
         department="生态环境部", region="全国", quality="B",
         summary="截至2025年6月底，全国碳市场配额累计成交量6.69亿吨、成交额459.29亿元；2024年全年成交额180.44亿元创历史新高，价格'指挥棒'作用逐步显现。",
         tags=["碳市场", "成交数据", "运行"]),

    # ---------- 减污降碳协同 ----------
    dict(title="《关于推进污水处理减污降碳协同增效的实施意见》",
         url="https://www.mee.gov.cn/",
         source="国家发展改革委、生态环境部等", date="2024-01-01", category="synergy",
         department="国家发改委", region="全国", quality="A",
         summary="指导协同推进污水处理全过程污染物削减与温室气体减排，提高污水处理综合效能，为减污降碳协同提供工程与技术支撑。",
         tags=["污水处理", "减污降碳协同", "实施意见"]),
    dict(title="《工业行业减污降碳协同增效评价 总则》等系列标准制定（50余项）",
         url="https://www.mee.gov.cn/xxgk2018/xxgk/xxgk13/202511/t20251114_1133711_wh.html",
         source="生态环境部、工信部", date="2025-07-25", category="synergy",
         department="生态环境部", region="全国", quality="B",
         summary="生态环境部配合工信部将减污降碳协同技术纳入国家鼓励工艺技术装备目录，指导制定《工业行业减污降碳协同增效评价 总则》等标准50余项，发布《国家重点推广的低碳技术目录（第五批）》，推广退役锂电池清洁循环利用等协同治理技术；组织88个城市开展碳污融合清单编制。",
         tags=["工业", "减污降碳协同", "评价标准", "碳污融合"]),
    dict(title="现代化国际大都市减污降碳协同创新试点工程（杭州）",
         url="https://www.hangzhou.gov.cn/art/2024/5/28/art_1229063385_1843507.html",
         source="杭州市", date="2024-05-21", category="synergy",
         department="杭州市", region="杭州", quality="A",
         summary="列入杭州国家碳达峰试点十大标志性工程之一，依托城市大脑与'杭碳云'，探索超大城市减污降碳协同路径，打造可复制的协同增效样板。",
         tags=["杭州", "减污降碳协同", "试点工程", "杭碳云"]),
    dict(title="国家碳达峰试点（杭州）建设经验（减污降碳协同方向）",
         url="https://www.ndrc.gov.cn/fggz/hjyzy/tdftzh/202412/t20241230_1395354.html",
         source="国家发展改革委", date="2024-12-30", category="synergy",
         department="国家发改委", region="全国", quality="A",
         summary="国家发改委刊发杭州试点经验：单位GDP能耗降至0.25吨标煤/万元（全省第一）；推进'核算+预算'制度、项目碳评、'杭碳'绿色金融品牌、'杭碳'标准；实施十大标志性工程（91个项目），强化数智、科技、金融特色优势。",
         tags=["杭州", "试点经验", "碳双控", "杭碳"]),

    # ---------- 行业低碳与节能降碳 ----------
    dict(title="《工业领域碳达峰实施方案》",
         url="https://www.mee.gov.cn/",
         source="工业和信息化部等", date="2024-01-01", category="industry",
         department="工信部", region="全国", quality="A",
         summary="部署工业领域碳达峰路径，推动钢铁、建材、石化化工、有色等重点行业节能降碳改造与绿色低碳转型，培育绿色工厂、绿色园区、绿色供应链。",
         tags=["工业", "碳达峰", "重点行业", "绿色制造"]),
    dict(title="《杭州市建筑领域碳达峰实施方案》（七部门联合印发）",
         url="https://jst.zj.gov.cn/art/2024/10/29/art_1569972_58936910.html",
         source="杭州市建委等七部门", date="2024-01-01", category="industry",
         department="杭州市建委", region="杭州", quality="A",
         summary="统筹经济增长、能源安全、碳排放、居民生活四维度，围绕标准提升、绿色建造、可再生能源应用、既有公共建筑能效提升、绿色生活五大领域20项举措；'十四五'计划实施公共建筑能效提升465万㎡；累计创建绿色低碳试点项目109个。",
         tags=["杭州", "建筑达峰", "绿色建筑", "能效提升"]),
    dict(title="新版《重点用能单位节能管理办法》",
         url="https://www.mee.gov.cn/",
         source="国家发展改革委", date="2024-01-01", category="industry",
         department="国家发改委", region="全国", quality="B",
         summary="强化重点用能单位节能管理，明确能耗在线监测、能源利用状况报告、节能目标责任，落实化石能源消费预算管理与碳排放管控要求。",
         tags=["重点用能单位", "节能管理", "办法"]),
    dict(title="杭州萧山区发布全省首个县（市、区）级国家碳达峰实施方案",
         url="https://www.toutiao.com/article/7449592199282573835/",
         source="萧山区政府/国网萧山供电", date="2024-12-18", category="industry",
         department="萧山区", region="杭州", quality="B",
         summary="浙江省首个县区级碳达峰实施方案。萧山为杭州工业强区，2023年碳排放2093万吨（工业占40.6%）；方案明确两阶段目标，打造全国碳达峰数智赋能标杆区，发挥电力在能源转型与碳减排中的关键作用。",
         tags=["杭州", "萧山", "县区级", "工业达峰"]),

    # ---------- 技术、产品与创新 ----------
    dict(title="《国家重点低碳技术征集推广实施方案》（环办气候〔2024〕2号）",
         url="https://sthjt.shaanxi.gov.cn/xxgk/fdnr/zcwj/shf/202403/t20240318_2989050.html",
         source="生态环境部等六部门", date="2024-01-01", category="tech",
         department="生态环境部", region="全国", quality="A",
         summary="明确五大重点方向（能源绿色低碳转型、重点领域降碳、储碳固碳、数智赋能、非二氧化碳减排）的低碳技术征集与推广机制，以技术降碳潜力为导向遴选示范类与推广类技术，为第五批目录奠定基础。",
         tags=["低碳技术", "征集推广", "实施方案"]),
    dict(title="国家电投5项技术入选《国家重点推广的低碳技术目录（第五批）》",
         url="https://www.toutiao.com/article/7476351762719326754",
         source="国家电投", date="2025-02-28", category="tech",
         department="国家电投", region="全国", quality="B",
         summary="入选技术含大型光伏电站智能柔性控制、压水堆核电厂热电联供、分布式光伏直流接入电解铝柔性直流微网、低能耗燃煤燃机烟气碳捕集、电动重卡快速换电补能，覆盖能源转型、工业降碳、储碳固碳、交通降碳4方向。",
         tags=["低碳技术", "国家电投", "光伏", "CCUS", "电动重卡"]),
    dict(title="杭州'双碳'成果转化首选地工程与虚拟电厂试点",
         url="https://news.bjx.com.cn/html/20240529/1379945.shtml",
         source="杭州市人民政府", date="2024-05-29", category="tech",
         department="杭州市", region="杭州", quality="A",
         summary="杭州试点建设虚拟电厂，全面挖掘工业、商业楼宇、数据中心、充电桩等柔性可调节资源；引导可再生能源项目配套储能（集中式风光按不低于装机10%配储），合理布局电网侧与用户侧储能，打造'双碳'成果转化首选地。",
         tags=["杭州", "虚拟电厂", "储能", "新型电力系统"]),

    # ---------- 国际与区域动态 ----------
    dict(title="国务院新闻办发布白皮书《碳达峰碳中和中国方案》",
         url="https://english.www.gov.cn/archive/whitepaper/202511/08/content_WS690ee812c6d00ca5f9a076cd.html",
         source="国务院新闻办公室", date="2025-11-08", category="intl_region",
         department="国务院新闻办", region="全国", quality="A",
         summary="白皮书系统总结中国五年来推进碳达峰碳中和的重大成就与实践路径，涵盖能源绿色低碳转型、重点领域深度减排、支撑保障体系、全球气候治理贡献；明确2025年9月习近平提出中国2035年国家自主贡献（NDC）目标，彰显负责任大国担当。",
         tags=["白皮书", "中国方案", "2035NDC", "气候治理"]),
    dict(title="杭州成功打造碳中和亚运会（首届碳中和亚运）",
         url="https://static.nfnews.com/content/202403/25/c8722668.html",
         source="杭州市", date="2023-10-08", category="intl_region",
         department="杭州市", region="杭州", quality="B",
         summary="杭州第19届亚运会历史首次实现碳中和：核算排放88.29万吨，使用绿电减排2.20万吨，接受社会捐赠碳抵消109.99万吨；首创碳中和亚运赛事标准，形成可复制大型赛事低碳样板。",
         tags=["杭州", "碳中和亚运", "大型活动", "绿电"]),
    dict(title="全国碳市场扩围前期：化工、石化、民航、造纸等行业扩围准备启动",
         url="https://www.news.cn/politics/20251124/1af45dd8c3034d47be23f0ec0c7c3ba2/c.html",
         source="新华社", date="2025-11-24", category="intl_region",
         department="生态环境部", region="全国", quality="B",
         summary="'十五五'规划建议提出扩大全国碳市场覆盖范围。生态环境部已启动化工、石化、民航、造纸等行业扩围前期准备（历史数据治理、技术文件编制、基础设施升级），到2027年基本覆盖工业领域主要排放行业。",
         tags=["碳市场", "扩围准备", "十五五", "行业覆盖"]),
]


def main():
    recs = []
    for it in ITEMS:
        r = dict(it)
        r["content"] = it.get("summary", "")
        r["content_fetched"] = False
        r["added_at"] = ADDED
        recs.append(r)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    json.dump(recs, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print("backfill inbox:", len(recs))


if __name__ == "__main__":
    main()
